
name: "Packer AMI 만들기"
on:
  push:
    branches:
      - master: # master 브랜치의 push 하면서
    paths:
      - "packer/**" # packer/ 하위경로에 변화가 있을때 동작하게 한다.
  workflow_dispatch: # 원할때 deploy 할 수 있는 옵션
jobs:
  packer_build: # 마음대로 가능
    runs-on: ubuntu-latest # 잠시빌려쓰는 ubuntu
    name: "Build AMI with packer & ansible"
    steps:
      - name: Checkout Repository # github 저장소로부터 소스코드 가져오기
        uses: actions/checkout@v4

      - name: Setup Packer # ubuntu 에 packer 설치
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      # 인증정보를 환경변수에 넣을수도 있지만 혹시 중간에 에러가 났을때 인증키가 로그에 노출될 수 있다.
      - name: Aws Configure # aws 인증정보 제공
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Packer Init & Build # 초기화와 빌드를 한번에
        run: |
          packer init .
          packer build .
        working-direcotry: ./packer

      - name: Setup Terraform # 테라폼 설치
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init & Apply # ./terraform 안에 있는 terraform 자원을 init, apply
        run: |
          terraform init
          terrafrom apply --auto-approve
        working-direcotry: ./terraform